import { Home as HomeIcon, Leaf, TrendingDown, Zap } from "lucide-react";

import { FeatureCard } from "~/components/cards/FeatureCard";
import { Container } from "~/components/layout/Container";
import { Section } from "~/components/layout/Section";
import { SectionHeader } from "~/components/layout/SectionHeader";
import { StaggerGroup, StaggerItem } from "~/components/motion/StaggerGroup";

const REASONS = [
  { icon: TrendingDown, title: "Lower Electricity Bills", description: "Generate your own power and reduce what you draw from the grid." },
  { icon: Zap, title: "Energy Independence", description: "Rely less on grid tariffs and outages for your day-to-day power." },
  { icon: Leaf, title: "Environmental Impact", description: "Every unit generated from sunlight is a unit not generated by burning fuel." },
  { icon: HomeIcon, title: "Increased Property Value", description: "A solar installation is a visible, lasting upgrade to the property." },
];

export function WhySolarSection() {
  return (
    <Section>
      <Container width="content">
        <SectionHeader id="why-solar-heading" eyebrow="Why Solar" title="Why homeowners and businesses are switching" />

        <StaggerGroup className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-4">
          {REASONS.map((reason) => (
            <StaggerItem key={reason.title}>
              <FeatureCard icon={reason.icon} title={reason.title} description={reason.description} />
            </StaggerItem>
          ))}
        </StaggerGroup>
      </Container>
    </Section>
  );
}
